---
- name: Add Disk to VMware VM
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  pre_tasks:
    - include_vars: vars_disk.yaml
  tasks:
    - name: Add a new disk to a VM
      community.vmware.vmware_guest_disk:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ item.value.vm_name }}"
        disk:
          - size_gb: "{{ item.value.disk_size }}"
            type: "{{ vm_disk_type }}"
            controller_type: "{{ vm_hw_scsi }}"
            datastore: "{{ item.value.datastore_name }}"
            controller_number: "{{ controller_number }}"
            unit_number: 1

          - size_gb: "{{ item.value.disk1_size }}"
            type: "{{ vm_disk_type }}"
            controller_type: "{{ vm_hw_scsi }}"
            datastore: "{{ item.value.datastore1_name }}"
            controller_number: "{{ controller_number }}"
            unit_number: 2
      delegate_to: localhost
      with_dict: "{{ myvms }}"

