version: '3'
services:
  controlnode:
    build: .
    networks:
    - my-network
    volumes:
      - ./play-with-ansible /ansible
  managenode1:
    image: centos:latest
    networks:
    - my-network
  managenode2:
    image: centos:latest
    networks:
    - my-network
  
  

